import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class RazorPayPaymentValidation {
  @ApiProperty({
    example: 'pay_29QQoUBi66xm2f',
    description: 'Razorpay payment id returned by razorpay checkout',
  })
  @IsString()
  @IsNotEmpty()
  razorpay_payment_id: string;

  @ApiProperty({
    example: 'order_9A33XWu170gUtm',
    description: 'Razorpay order id returned by the checkout',
  })
  @IsString()
  @IsNotEmpty()
  razorpay_order_id: string;

  @ApiProperty({
    example: '5d2b7f5f3a2e4a1b8e5e5d2b7f5f3a2e4a1b8e5e',
    description:
      'The signature generated by Razorpay checkout after payment to validate the payment',
  })
  @IsString()
  @IsNotEmpty()
  razorpay_signature: string;
}
